<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verano product configurator</title>
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
    <!--[if lt IE 9]>
        <script src="js/shiv/html5shiv.min.js"></script>
        <script src="js/shiv/html5shiv-printshiv.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="wrapper">
    <form action="">
        <div class="product-configurator-wrap">
            <div class="topbar">
                <button class="btn btn-blue icon"><i><?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="17" height="17" viewBox="0 0 17 17">
<g>
</g>
	<path d="M14.164 0h-12.664c-0.827 0-1.5 0.673-1.5 1.5v14c0 0.827 0.673 1.5 1.5 1.5h14c0.827 0 1.5-0.673 1.5-1.5v-12.724l-2.836-2.776zM8 1v4h3v-4h1v5h-8v-5h4zM3 16v-6h11v6h-11zM16 15.5c0 0.275-0.225 0.5-0.5 0.5h-0.5v-7h-13v7h-0.5c-0.276 0-0.5-0.225-0.5-0.5v-14c0-0.275 0.224-0.5 0.5-0.5h1.5v6h10v-6h0.756l2.244 2.196v12.304z" fill="#000000" />
</svg>
</i>Sla configuratie op</button>
            </div>
            <div class="slide">
                <div class="half">
                    <h2 class="step-title">Stap 1: Type kap</h2>
                    <p>Ben jij op een zonnige dag ook het liefst de hele dag buiten? Met zonneschermen bepaal jij de hoeveelheid zonlicht en de temperatuur op jouw terras.</p>
                    <p>Ben jij op een zonnige dag ook het liefst de hele dag buiten? Met zonneschermen bepaal jij de hoeveelheid zonlicht en de temperatuur op jouw terras. <a href="#" class="lightbox">Bekijk voorbeelden.</a></p>
                    
                    <?php /*
                    <div class="form-button-group">
                    <label class="switch"><input type="checkbox" id="togBtn"><div class="slider"><!--ADDED HTML --><span class="on">Standaard</span><span class="off">Ritz</span><!--END--></div></label>
                    </div>
                    */ ?>
                    <div class="form-row">
                        <div class="form-check-inline form-inline w-50">
                            <h3>Geleider links</h3>
                            <span class="checkbox">
                                <input class="form-check-input" type="checkbox" id="geleider_links_std" value="Standaard">
                                <label class="form-check-label" for="geleider_links_std">Standaard</label>
                            </span>
                            <span class="checkbox">
                                <input class="form-check-input" type="checkbox" id="geleider_links_ritz" value="Ritz">
                                <label class="form-check-label" for="geleider_links_ritz">Ritz</label>
                            </span>
                        </div> 
                        <div class="form-check-inline form-inline w-50">
                            <h3>Geleider rechts</h3>
                            <span class="checkbox">
                                <input class="form-check-input" type="checkbox" id="geleider_rechts_std" value="Standaard">
                                <label class="form-check-label" for="geleider_rechts_std">Standaard</label>
                            </span>
                            <span class="checkbox">
                                <input class="form-check-input" type="checkbox" id="geleider_rechts_ritz" value="Ritz">
                                <label class="form-check-label" for="geleider_geleider_rechts_ritzlinks_ritz">Ritz</label>
                            </span>
                        </div>
                        <div class="form-inline w-100">
                            <h3>Onderlijst</h3>
                            <select class="select-css">
                                <option>This is a native select element</option>
                                <option>Apples</option>
                                <option>Bananas</option>
                                <option>Grapes</option>
                                <option>Oranges</option>
                            </select>
                        </div> 
                    </div>
                </div>
                <div class="half">
                    <div class="product-image">
                        <figure>
                            <img src="img/V210-Rhodos.jpg" alt="">
                        </figure>
                    </div>
                </div>
            </div>
            <div class="details">
                <h4>Configuratie</h4>
                <div class="list-wrap">
                    <dl>
                        <dt>Soort scherm</dt>
                        <dd>Ritz scherm</dd>
                    </dl>
                    <dl>
                        <dt>Type scherm</dt>
                        <dd>V540</dd>
                    </dl>
                    <dl>
                        <dt>Type kap</dt>
                        <dd>Rechte kap</dd>
                    </dl>
                </div>
                <button class="btn btn-yellow icon right animate" id="next-step">Volgende stap <i><svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><title>ionicons-v5-a</title><polyline points="268 112 412 256 268 400" style="fill:none;stroke:#fff;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px"/><line x1="392" y1="256" x2="100" y2="256" style="fill:none;stroke:#fff;stroke-linecap:round;stroke-linejoin:round;stroke-width:48px"/></svg></i></button>
            </div>    
        </div>
    </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="js/vendor/modernizr-custom.js"></script>
<script src="js/main.js"></script>
</body>
</html>